Hotfix/token response
in2workspace/in2-verifier-core-api pull request #14
Opened 2024-11-12 16:55 UTC by rubenmodamioin2

### Fixed
- Token response fix to comply with the OpenID Connect Core standard.

2024-11-12 20:26 UTC, oriolcanades requested changes

2024-11-12 20:26 UTC, oriolcanades commented on src/main/java/es/in2/vcverifier/config/properties/SecurityProperties.java
> +        this.token = Optional.ofNullable(token).orElse(new TokenProperties(null, null));
Vigila con establecer el objeto vacío. Deberíamos establecer una configuración por defecto o no dejar que el aplicativo se instancie si no está correctamente definido.

2024-11-12 20:26 UTC, oriolcanades commented on src/main/java/es/in2/vcverifier/config/properties/SecurityProperties.java
> +            this.accessToken = Optional.ofNullable(accessToken).orElse(new AccessTokenProperties("1", MINUTES));
Por qué el accessToken tiene una vida útil de 1 minuto? No debería ser al revés? El access_token debe tener una vida útil de 30 minutos? Qué pasa con el refresh token?

2024-11-13 06:38 UTC, rubenmodamioin2 commented on src/main/java/es/in2/vcverifier/config/properties/SecurityProperties.java
> +            this.accessToken = Optional.ofNullable(accessToken).orElse(new AccessTokenProperties("1", MINUTES));
Si, están al revés, creo que 30 min para el access_token esta bien ya que no ofrecemos refresh token.

2024-11-13 07:10 UTC, rubenmodamioin2 commented on src/main/java/es/in2/vcverifier/config/properties/SecurityProperties.java
> +        this.token = Optional.ofNullable(token).orElse(new TokenProperties(null, null));
Resuelto aplicando validaciones @NotBlank y @NotNull para campos obligatorios y estableciendo valores por defecto en los opcionales mirando si son nulos o están vacíos, garantizando así que la aplicación tenga configuraciones válidas al iniciar.

2024-11-13 07:36 UTC, oriolcanades approved these changes

2024-11-13 09:13 UTC, merged