feature/verifier-h2m-m2m-flows
in2workspace/in2-verifier-core-api pull request #4
Opened 2024-09-25 08:08 UTC by javieralvarezin2

- Spring Security setup with OIDC support and custom authentication filters.
- Cryptographic components for ECKey (P-256) generation and JWT management.
- Controllers for handling QR login flows, authentication requests, and DID resolution.
- OID4VP support: Services to process Verifiable Presentation (VP) submissions and validate client assertions.
- Caching: Implemented in-memory caching (JWT, OAuth2 data) with expiration and JTI token tracking for replay prevention.
- Dynamic OAuth2 client loading from JSON with custom settings (JWK, Proof Key).

2024-09-25 08:22 UTC, albertorubioin2 commented on src/main/resources/static/css/style.css
Vigilar cuando ponemos valores en px, los casos implementados esta ok, pero en margenes y paddings quizás pueda dar problemas en movil.
Lo mismo con los porcentajes, no son muy recomendables pero para este caso esta bien :)

2024-09-25 09:08 UTC, albertrodriguezdev requested changes

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/VcVerifierApplication.java
> +                    .configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true)
The SORT_PROPERTIES_ALPHABETICALLY setting only works for POJOs, is it being taken into account?

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/config/CacheStore.java
> +        if (key != null && !key.trim().isEmpty() && value != null) {
Use .isBlank() instead of .trim().isEmpty()
(https://www.baeldung.com/java-string-isempty-vs-isblank#looking-at-java-11s-stringisblank)

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/config/ClientLoaderConfig.java
> +                if (clientData.getClientSecret() != null && !clientData.getClientSecret().isEmpty()) {
Could you check the blank spaces?

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/crypto/CryptoConfig.java
> +        if (privateKey.contains("0x")) {
Could use "startsWith" instead of "contains", because "0x" only can be in the beginning of the key.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/model/ClientData.java
Could it be a record?

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/model/LEARCredentialEmployee.java
Records should not be nested, but rather organized with packages.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/model/LEARCredentialMachine.java
Records should not be nested, but rather organized with packages.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/config/CacheStore.java
> +    // Obtener el valor directamente sin Mono
This app doesn't use Mono.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/config/CacheStore.java
> +    // Eliminar un valor de la caché sin Mono
This app doesn't use Mono.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/config/CacheStore.java
> +    // Añadir un valor a la caché sin Mono
This app doesn't use Mono.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/oid4vp/controller/LoginQrController.java
> +            throw new RuntimeException();
You must throw a custom exception instead of a generic.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/oid4vp/controller/LoginQrController.java
> +    @GetMapping("/login")
Use "@ResponseStatus" to specify de default response. (https://www.baeldung.com/spring-response-status)

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/oid4vp/controller/Oid4vpController.java
> +    @GetMapping("/auth-request/{id}")
Use "@ResponseStatus" to specify de default response if only use ResponseEntity to return status and body. (https://www.baeldung.com/spring-response-status)

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/oid4vp/controller/Oid4vpController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND)
Throw a custom exception to return an error.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/oid4vp/controller/Oid4vpController.java
> +    @PostMapping("/auth-response")
Use "@ResponseStatus" to specify de default response. (https://www.baeldung.com/spring-response-status)

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/oid4vp/service/impl/AuthorizationResponseProcessorServiceImpl.java
> +        Instant issueTime = Instant.now();
In future use Instant with a Clock to facilitate Unit Tests.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/resolver/CustomJWKS.java
Records should not be nested, but rather organized with packages.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/resolver/ResolverController.java
> +    @GetMapping("/{id}")
Use "@ResponseStatus" to specify de default response. (https://www.baeldung.com/spring-response-status)

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/security/SecurityConfig.java
Enable CORS?

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/DIDServiceImpl.java
> +            throw new RuntimeException("JWT signature verification failed.", e);
Use custom exception.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/JWTServiceImpl.java
> +            throw new RuntimeException("JWT signature verification failed.", e);
It must be a custom exception.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/JWTServiceImpl.java
> +            throw new RuntimeException(e);
Custom exception.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/TrustFrameworkServiceImpl.java
> +            throw new RuntimeException("Error reading clients list from GitHub.", e);
Custom exception.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/TrustFrameworkServiceImpl.java
> +            throw new RuntimeException("Error reading issuer ID list from GitHub.", e);
Custom exception.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/TrustFrameworkServiceImpl.java
> +            throw new RuntimeException("Error reading participant ID list from GitHub.", e);
Custom exception.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/VpServiceImpl.java
> +            throw new RuntimeException("Error converting VC to LEARCredentialMachine", e);
Custom exception.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/VpServiceImpl.java
> +            throw new RuntimeException("Error converting VC to LEARCredentialEmployee", e);
Custom exception.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/VpServiceImpl.java
> +            throw new RuntimeException("Error parsing the Verifiable Presentation or Verifiable Credential", e);
Custom exception.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/VpServiceImpl.java
> +            throw new RuntimeException("The 'verifiableCredential' claim was not found within 'vp'");
Custom exception.

2024-09-25 09:08 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/VpServiceImpl.java
> +        throw new Exception("Organization Identifier not found in certificates.");
Custom exception.

2024-09-25 14:09 UTC, albertrodriguezdev requested changes

2024-09-25 14:09 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/exception/handler/CustomExceptionHandler.java
- Rename class to GlobalExceptionHandler.
- Change @ControllerAdvice to @RestControllerAdvice.
- Extends from ResponseEntityExceptionHandler.
- Use @ResponseEntity in every method instead of return ResponseEntity.
- Return every method with a GlobalErrorResponse => `public record GlobalErrorMessage(String title, String message, String path) {
}` instead of the String.

Reference: https://github.com/oriolcanades/blog/blob/main/posts/post-8-manejo-global-excepciones/2024-03-09-manejo-global-excepciones.md#globalexceptionhandler

2024-09-25 15:14 UTC, albertrodriguezdev approved these changes

2024-09-25 15:32 UTC, albertrodriguezdev requested changes

2024-09-25 15:32 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/exception/handler/GlobalExceptionHandler.java
Check if works with a Controller.

2024-09-26 15:32 UTC, albertrodriguezdev requested changes

2024-09-26 15:32 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/config/ApiConfig.java
> +        if (profiles.isEmpty()) {
Must check if null and isBlank

2024-09-26 15:32 UTC, albertrodriguezdev commented on src/main/java/es/in2/vcverifier/service/impl/AllowedClientsServiceImpl.java
> +        if (profile == null) {
Must check also if isBlank

2024-09-27 06:07 UTC, albertrodriguezdev submitted a review, later dismissed

2024-09-27 07:28 UTC, albertrodriguezdev submitted a review, later dismissed

2024-09-30 06:51 UTC, albertrodriguezdev submitted a review, later dismissed

2024-09-30 07:31 UTC, albertrodriguezdev submitted a review, later dismissed

2024-09-30 07:54 UTC, albertrodriguezdev submitted a review, later dismissed

2024-10-02 10:50 UTC, albertrodriguezdev submitted a review, later dismissed

2024-10-04 10:26 UTC, albertrodriguezdev submitted a review, later dismissed

2024-10-04 13:52 UTC, albertrodriguezdev submitted a review, later dismissed

2024-10-07 06:24 UTC, albertrodriguezdev submitted a review, later dismissed

2024-10-07 06:56 UTC, albertrodriguezdev submitted a review, later dismissed

2024-10-07 08:59 UTC, albertrodriguezdev submitted a review, later dismissed

2024-10-07 10:16 UTC, albertrodriguezdev submitted a review, later dismissed

2024-10-08 12:06 UTC, albertrodriguezdev approved these changes

2024-10-08 12:26 UTC, merged